version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/projeto-grafos:delegated"
    environment:
      START_CMD: "python -m src.main"
    command: ["sh", "-c", "${START_CMD}"]